### ISSUE TITLE
Error running the project

### ISSUE THREAD

**Issue by frasza** [nuxt/devtools#50]
I have enabled devtools for the project running Nuxt 3.2.0 and whenever I run `nuxi dev` I get the following output:

```
Nuxt 3.2.0 with Nitro 2.2.1                                                                                                                                                                                                        13:05:40  
                                                                                                                                                                                                                                   13:05:41  
  > Local:    http://localhost:3000/
  > Network:  http://172.21.0.1:3000/
  > Network:  http://192.168.1.122:3000/

i Using default Tailwind CSS file from runtime/tailwind.css                                                                                                                                                       nuxt:tailwindcss 13:05:42  
√ Nuxt Devtools is enabled v0.1.2 (experimental)                                                                                                                                                                                   13:05:42  
i Tailwind Viewer: http://localhost:3000/_tailwind/                                                                                                                                                               nuxt:tailwindcss 13:05:43  

ERROR  Failed to load url /@fs/C:/Users/user/AppData/Roaming/nvm/v16.18.0/node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector/src/load.js (resolved id: C:/Users/user/AppData/Roaming/nvm/v16.18.0/node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector/src/load.js?v=d57f6aaf). Does the file exist?

ERROR  Failed to load url /@fs/C:/Users/user/AppData/Roaming/nvm/v16.18.0/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.mjs?v=d57f6aaf (resolved id: C:/Users/user/AppData/Roaming/nvm/v16.18.0/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.mjs?v=d57f6aaf). Does the file exist?
                                                                                                                                                                                                                                   13:05:40  
i Vite client warmed up in 4084ms 13:05:48  
√ Nitro built in 1235 ms
```

Any ideas? Maybe related to `nvm` usage or something similar?

**Comment by Cosnavel** [comment]
Same issue here

**Comment by afflexux** [comment]
This gets rid of the globally installed DevTools so it doesn't cause problems with other Nuxt projects.

https://github.com/nuxt/devtools/issues/46#issuecomment-1425426414

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by mario-neuhold** [comment]
it happens on a blank nuxt3 install on windows, can't really reproduce it based on a repo:

```cli
$ npx nuxi init nuxt-devtools-test
$ cd nuxt-devtools-test
$ yarn
$ npx nuxi@latest devtools enable
$ yarn dev
```
as others mentioned, it is working with v0.1.2 when devtools are added manually in a project. also might be related to nvm for windows, which probably every windows nuxt user is using.

**Comment by cryptopay-pavel** [comment]
Same here. I can't remove error message even removing all global libraries related to nuxt ecosystem.
Still getting error in console for any nuxt project:
` ERROR  Cannot start nuxt:  Cannot find module '/Users/pas/.nvm/versions/node/v16.17.0/lib/node_modules/@nuxt/devtools/module.cjs'
Require stack:
- /Users/pas/projects/rein/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:244204)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:260:29)
  at normalizeModule (node_modules/@nuxt/kit/dist/index.mjs:448:18)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:434:47)
  at initNuxt (node_modules/nuxt/dist/index.mjs:2044:13)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6797:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6858:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:51:20)`

**Comment by mfrascati** [comment]
Same on Mac

```
 ERROR  Cannot start nuxt:  Cannot find package 'vite' imported from [...]/.nvm/versions/node/v18.13.0/lib/node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector/dist/index.mjs                               22:33:13

  at new NodeError (internal/errors.js:322:7)
  at packageResolve (internal/modules/esm/resolve.js:732:9)
  at moduleResolve (internal/modules/esm/resolve.js:773:18)
  at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
  at Loader.resolve (internal/modules/esm/loader.js:89:40)
  at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
  at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
  at link (internal/modules/esm/module_job.js:75:36)
```

running the global install breaks it, after removing it local install works.

**Comment by cryptopay-pavel** [comment]
Sorry for my level of English, but I think I found solution:
It happens because we using nvm but devtools is installed in 'system' node_modules directory.
If you want to continue using this tool - change node version in nvm to system using command 'nvm use system' or do manual installation.
if you want to get rid of errors in the console - go to system node_modules path (/usr/local/lib/node_modules/ for darwin os) and remove @nuxt folder.
I hope this helps.

**Comment by antfu** [comment]
It should be fixed in the latest version, please run `npx nuxi@latest devtools enable` again.

**Comment by L422Y** [comment]
I'm having what I believe is same issue, I updated my nvm version of node to 18.16 and it's still referencing 18.8 nvm folder. I've cleared my lock files, node_modules, .nuxt. I can't even seem to enable/disable devtools properly.

if i run `npx nuxi@latest devtools disable` and have:
```
  devtools: {
        enabled: true
    }
```
I get:
```
Disabling Nuxt Devtools...                                                             
ℹ Nuxt Devtools is already disabled
✔ Nuxt Devtools disabled for this project.
```
And if I set it to enabled: false and run `npx nuxi@latest devtools disable`, it tries to enable it..

**Comment by L422Y** [comment]
Looks like the absolute path was being stored in `~/.nuxtrc`
```
modules.0=/Users/[redacted]/.nvm/versions/node/v18.8.0/lib/node_modules/@nuxt/devtools/dist/module.mjs
```

**Comment by SebbeJohansson** [comment]
@L422Y THanks! that was the solution for me.

**Comment by codeflorist** [comment]
> I think this issue only happened with npm because I tried it with yarn and it is working correctly.

no, had the same problem with yarn. this is evil. didn't even know, that there was a `~/.nuxrc`.

**Comment by leosin** [comment]
When I used nvm to switch to version 16 before, an error would be reported, `ERROR  Cannot find module '/Users/<userbane>/.nvm/versions/........`
Now, I use `nvm use system` to switch to the system version 18.xx, and no error is reported.

**Comment by calebsmithdev** [comment]
> 

Confirmed that removing this hidden file fixed it for me on the Mac as well.

**Comment by xiaoluoboding** [comment]
> npx nuxi@latest devtools enable

when you upgrade the node version, the version of the `.nuxtrc` file does not change.
